name: lstn

on:
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  pull-requests: write

jobs:
  lstn:
    name: "lstn"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3
      - uses: listendev/action@v0.1.0
        with:
          flags: "--endpoint=https://npm-staging.listen.dev"
