name: lstn action reference workflow
on:
  push:
    branches: ['*']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lstn:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: lstn scan
        uses: garnet-org/lstn-gh-action@0.0.1
        with:
          lstn-command: 'scan'
          workdir: '.'

      - name: Display results
        run: cat lstn-output.json

      - name: lstn policy
        uses: garnet-org/lstn-gh-action@0.0.1
        with:
          apply-policy: true
          rules-file: 'rules.yml'
          rule-name: 'ignore_priority_medium'
