name: Example workflow using lstn Docker action
on:
  pull_request:
    branches: ["main"]

jobs:
  lstn-docker-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: lstn scan
        uses: garnet-org/lstn-gh-action@0.0.1
        with:
          lstn-command: 'scan'
          workdir: '.'

      - name: Display lstn verdicts
        run: cat lstn-output.json

      - name: lstn policy
        uses: garnet-org/lstn-gh-action@0.0.1
        with:
          apply-policy: true
          rules-file: 'rules.yml'
          rule-name: 'ignore_priority_medium'
          
      - name: Run npm install
        run: echo "Installing dependencies..." && npm install .