name: lstn scan

on:
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  pull-requests: write

jobs:
  lstn:
    name: "lstn"
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Run lstn scan
        uses: listendev/action@v0.1.0

      - name: Enforce lstn policy
        uses: garnet-org/lstn-policy@main
        with:
          workdir: '.'
          apply-policy: true
          rules-file: 'rules.yml'
          rule-name: 'ignore_priority_medium'
